services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eb_bijuteria_web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev